### ISSUE TITLE
Does not detect newer yubikeys

### ISSUE THREAD

**Issue by npmccallum** [Yubico/python-yubico#17]
>>> import yubico; yubico.find_yubikey()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/yubico/yubikey.py", line 242, in find_key
    raise YubiKeyError('No YubiKey found')
yubico.yubikey.YubiKeyError: <YubiKeyError instance at 0x7f120235ce60: No YubiKey found>

Adding the new PIDs to /usr/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py results in a discovered device, but a new error:

>>> import yubico; yubico.find_yubikey()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/yubico/yubikey.py", line 229, in find_key
    YK = YubiKeyUSBHID(debug=debug, skip=skip)
  File "/usr/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 141, in __init__
    if not self._open(skip):
  File "/usr/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 440, in _open
    self._usb_handle.setConfiguration(1)
  File "/usr/lib/python2.7/site-packages/usb/legacy.py", line 253, in setConfiguration
    self.dev.set_configuration(configuration)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 799, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 128, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 730, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy

No problems are observed on older yubikeys. lsusb output is:
  idVendor           0x1050 Yubico.com
  idProduct          0x0116 
  bcdDevice            3.32
  iManufacturer           1 Yubico
  iProduct                2 Yubikey NEO OTP+U2F+CCID
  iSerial                 0 
  bNumConfigurations      1

**Comment by dainnilsson** [comment]
This should now be fixed in 1.2.3.

**Comment by npmccallum** [comment]
I'm still getting:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/yubico/yubikey.py", line 229, in find_key
    YK = YubiKeyUSBHID(debug=debug, skip=skip)
  File "/usr/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 141, in __init__
    if not self._open(skip):
  File "/usr/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 440, in _open
    self._usb_handle.setConfiguration(1)
  File "/usr/lib/python2.7/site-packages/usb/legacy.py", line 253, in setConfiguration
    self.dev.set_configuration(configuration)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 799, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 128, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 730, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
